// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/changelog" | "/como-funciona" | "/dashboard" | "/dashboard/caixinhas" | "/dashboard/carteira" | "/dashboard/configuracoes" | "/dashboard/credenciais" | "/dashboard/depositos" | "/dashboard/metas" | "/dashboard/taxas" | "/dashboard/transferencias" | "/login" | "/offline" | "/termos"
type AppRouteHandlerRoutes = "/api/auth/google" | "/api/auth/login" | "/api/auth/register" | "/api/auth/verify" | "/api/changelog" | "/api/credentials" | "/api/dashboard" | "/api/deposits" | "/api/notifications" | "/api/notifications/discord" | "/api/security/2fa" | "/api/security/validate-pin" | "/api/transfers" | "/api/users/search" | "/api/webhooks"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/google": {}
  "/api/auth/login": {}
  "/api/auth/register": {}
  "/api/auth/verify": {}
  "/api/changelog": {}
  "/api/credentials": {}
  "/api/dashboard": {}
  "/api/deposits": {}
  "/api/notifications": {}
  "/api/notifications/discord": {}
  "/api/security/2fa": {}
  "/api/security/validate-pin": {}
  "/api/transfers": {}
  "/api/users/search": {}
  "/api/webhooks": {}
  "/changelog": {}
  "/como-funciona": {}
  "/dashboard": {}
  "/dashboard/caixinhas": {}
  "/dashboard/carteira": {}
  "/dashboard/configuracoes": {}
  "/dashboard/credenciais": {}
  "/dashboard/depositos": {}
  "/dashboard/metas": {}
  "/dashboard/taxas": {}
  "/dashboard/transferencias": {}
  "/login": {}
  "/offline": {}
  "/termos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
